### ISSUE TITLE
Notify users in case output syntax requires `myst` extensions

### ISSUE THREAD

**Issue by mbercx** [executablebooks/rst-to-myst#15]
When converting to `myst` syntax that requires extensions, it would be good in case the user was made aware of these required extensions somehow. 

The description below was my original post, which thought the conversion was buggy because I wasn't aware of the extension `colon_fence`.

---

**Describe the bug**

When converting e.g. a `figure` directive 

```rest
.. _fig_intro_workchain_graph:
.. figure:: include/images/basics_workchain_graph.png
    :scale: 30
    :align: center

    Provenance Graph of a basic AiiDA WorkChain.
```

This gets converted into

```markdown

(fig-intro-workchain-graph)=
:::{figure} include/images/basics_workchain_graph.png
:scale: 30
:align: center

Provenance Graph of a basic AiiDA WorkChain.

:::
```

**Expected behavior**

Doesn't `myst-nb` need backticks for the directives? I.e. if I convert this into 

```markdown
(fig-intro-workchain-graph)=

```{figure} include/images/basics_workchain_graph.png
:scale: 30
:align: center

Provenance Graph of a basic AiiDA WorkChain.
```#
```
This works fine for me.

Similar issues arise for `note` and `important` directives (and possibly others that are not in the file I'm converting).

**Environment**

- Python Version [e.g. 3.7.1]: 3.8.6
- Package versions or output of `jupyter-book --version`:
  ```console
  $ pip freeze | grep myst
  myst-nb==0.13.0a1
  myst-parser==0.14.0a2
  rst-to-myst==0.1.2
  ```
- Operating System: macOS Big Sur 11.3.1

**Comment by mbercx** [comment]
Title should be:

Some directives convert into `:::{<directive>}`, not `` ```{<directive>}``

But if I copy paste this into the Title and save it, it doesn't work. 🤨

This is seriously triggering my OCD. 😅

**Comment by chrisjsewell** [comment]
See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html, you can add `colon_fence` to the myst extensions to also allow for colons.
(But yeh I intend to make it clearer with this tool when it is outputting syntax that requires extensions)

**Comment by mbercx** [comment]
Update title and OP, can't change label unfortunately 😭
