### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by fmfreeze** [executablebooks/rst-to-myst#35]
### Describe the bug

When using on Windows10 with the command `rst2myst convert *.rst`
it produces:

```
Usage: rst2myst convert [OPTIONS] [PATHS]...
Try 'rst2myst convert -h' for help.

Error: Invalid value for '[PATHS]...': Path '*.rst' does not exist.
```

I triple-checked the if I am in the right directory, where my .rst files are stored.
Also tried quoting the path.

Does anybody experienced that issue? On Linux it worked as expected.

### Reproduce the bug

1. in a conda environment install with `pip install rst-to-myst[sphinx]`
2. in terminal navigate to the folder where *.rst files are stored
3. execute the command `rst2myst convert *.rst`

**Comment by Joinyy** [comment]
@fmfreeze You can get it working when upgrading your click package to 8.1.3, this works for me on python 3.8 and 3.10 on windows.

**Comment by slavakx** [comment]
> @fmfreeze You can get it working when upgrading your click package to 8.1.3, this works for me on python 3.8 and 3.10 on windows.

Yes it works when installed directly with pip. However, when installed via poetry I get the following error:

```
Because rst-to-myst (0.3.2) depends on click (>=7.1,<8.0)
and no versions of rst-to-myst match >0.3.2,<0.4.0, rst-to-myst (>=0.3.2,<0.4.0) requires click (>=7.1,<8.0)
```

It would be good to have this issue solved. I spent the whole day trying to understand what is wrong with the path

**Comment by chrisjsewell** [comment]
v0.3.3 (just released) now allows click v8
